[package]
name = "market-data-source"
version = "0.1.0"
edition = "2024"

[features]
std = [
    "serde?/std",
    "serde_json?/std",
]
alloc = [
    "serde?/alloc",
    "serde_json?/alloc",
]
api-emulator = []
api-emulator-yfinance = ["api-emulator"]
api-emulator-tdameritrade = ["api-emulator"]
simd_support = ["rand/simd_support"]
std_math = ["rand_distr/std_math"]
serde = ["dep:serde"]
couchdb = ["dep:couch_rs", "tokio", "serde", "serde_json"]
serde_json = ["dep:serde_json"]
csv_export = ["dep:csv", "serde"]
json_export = ["serde", "serde_json"]
tokio = ["dep:tokio"]
dotenvy = ["dep:dotenvy"]
# api-emulator-alpha-vantage = ["api-emulator"]
# api-emulator-iex-cloud = ["api-emulator"]
# api-emulator-twelve-data = ["api-emulator"]
# api-emulator-finnhub = ["api-emulator"]
# api-emulator-coin-gecko = ["api-emulator"]
# api-emulator-coin-market-cap = ["api-emulator"]
# api-emulator-crypto-compare = ["api-emulator"]
# api-emulator-binance = ["api-emulator"]
# api-emulator-kraken = ["api-emulator"]
# api-emulator-coinbase = ["api-emulator"]
# api-emulator-bitstamp = ["api-emulator"]
# api-emulator-bitfinex = ["api-emulator"]
# Optional features can be defined here
# For example:
# - "serde": "1.0"
# - "tokio": { version = "1.0", optional = true }

[dependencies]
couch_rs = { version = "0.12.1", optional = true }
csv = { version = "1.3.1", optional = true }
dotenvy = { version = "0.15.7", optional = true }
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.143", optional = true }
tokio = { version = "1.47.1", features = ["rt", "macros"], optional = true }


[dev-dependencies]
tempfile = "3.8"

[lib]
name = "market_data_source"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]
