[package]
name = "market-data-source"
version = "0.1.0"
edition = "2024"

[features]
std = [
    "serde?/std",
    "serde_json?/std",
]
alloc = [
    "serde?/alloc",
    "serde_json?/alloc",
]
api-emulator = []
api-emulator-yfinance = ["api-emulator"]
api-emulator-tdameritrade = ["api-emulator"]
simd_support = ["rand/simd_support"]
std_math = ["rand_distr/std_math"]
serde = ["dep:serde"]
couchdb = ["dep:couchdb"]
serde_json = ["dep:serde_json"]
# api-emulator-alpha-vantage = ["api-emulator"]
# api-emulator-iex-cloud = ["api-emulator"]
# api-emulator-twelve-data = ["api-emulator"]
# api-emulator-finnhub = ["api-emulator"]
# api-emulator-coin-gecko = ["api-emulator"]
# api-emulator-coin-market-cap = ["api-emulator"]
# api-emulator-crypto-compare = ["api-emulator"]
# api-emulator-binance = ["api-emulator"]
# api-emulator-kraken = ["api-emulator"]
# api-emulator-coinbase = ["api-emulator"]
# api-emulator-bitstamp = ["api-emulator"]
# api-emulator-bitfinex = ["api-emulator"]
# Optional features can be defined here
# For example:
# - "serde": "1.0"
# - "tokio": { version = "1.0", optional = true }

[dependencies]
couchdb = { version = "0.6.0", optional = true }
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.143", optional = true }


[lib]
name = "market_data_source"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]
